### PR TITLE
Add hashCode() and equals() to Submission to prevent duplicates

### PR DESCRIPTION
**Pull request by fbis251**
This will allow you to easily prevent duplicates by using a Set. For
example, using a LinkedHashSet to store Frontpage Submissions will
make sure that you only have unique posts since the reddit API will
sometimes return duplicates when requesting more posts.

### CODE REVIEW

**Comment by thatJavaNerd** [comment]
This is a very nice change. Why not include these methods where they can be utilized by any object that has an ID, say in `Thing`? That way every `Thing` subclass has access to a basic `equals` and `hashCode` method.

**Comment by fbis251** [comment]
Okay I have updated the pull request to use the Thing class.

**Comment by fbis251** [comment]
Hey, any update on adding this?

**Comment by thatJavaNerd** [comment]
Yeah I'm sorry I haven't been able to do much work on this project lately. Thanks for the pull request!

**Pull request merged**
