### PR TITLE
OkHttpAdapter: Allow using raw_json=1 with reddit's API responses

### PR DESCRIPTION
**Pull request by fbis251**
https://www.reddit.com/dev/api/

The reddit API documentation states:
"response body encoding

For legacy reasons, all JSON response bodies currently have <, >, and &
replaced with &lt;, &gt;, and &amp;, respectively. If you wish to opt out of
this behaviour, add a raw_json=1 parameter to your request."

### CODE REVIEW

**Comment by ccrama** [comment]
Implemented this on Slide a month ago and it's working well! A disclaimer though, some strings are still escaped, like quotes and slashes, so escaping the strings is still necessary before displaying them

**Comment by fbis251** [comment]
@ccrama Just a heads up, it looks like you implemented this using a header instead of a query parameter in your fork, when I checked out the reddit response the < > and & characters were still encoded.

I used Slide v5.5-alpha4 to check

**Comment by ccrama** [comment]
Really? Maybe that is why it was not decoding everything... My bad!

**Comment by thatJavaNerd** [comment]
I haven't heard of this parameter before. Is it new? Do you have an example of its effect?

**Comment by fbis251** [comment]
Sure, like the documentation states, it will not encode the 3 characters in the responses. It's most useful for URLs that contain ampersands such as the preview size variations,


```
Without raw_json=1
https://i.redditmedia.com/ESe2OruwN9TK2GA4MbPbKQgUM4wDVm_F1CuYXG-yA1I.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=71e9d6f9e9691afd0cf912ffed52067a

With raw_json=1
https://i.redditmedia.com/ESe2OruwN9TK2GA4MbPbKQgUM4wDVm_F1CuYXG-yA1I.jpg?fit=crop&crop=faces%2Centropy&arh=2&w=320&s=71e9d6f9e9691afd0cf912ffed52067a
```

This makes it easier for the client to not have to parse each URL as HTML to decode the characters since the API itself will send the characters decoded.

**Comment by thatJavaNerd** [comment]
While its useful change, I do not think OkHttpAdapter is the most appropriate place for this patch. What if the client writes their own HttpAdapter? We should enable this parameter as needed in request functions.

**Comment by fbis251** [comment]
We could add the method to the HttpAdapter interface since every other client can add the parameter to the request URL pretty easily.

The reason I think that we should have an option for this is that raw_json=1 will work with essentially every request that contains < > or & in the response. From what I have seen there are no adverse effects from including the parameter in every request (even authentication calls)

**Comment by thatJavaNerd** [comment]
What would you have this method look and function like?

**Comment by fbis251** [comment]
The simplest way would be to have it take in the original URL, add the query parameters within the method and return a java.net.URL that has the original URL with the added query parameter. We could also add the setRawJson() method in the interface since that's the easiest way to toggle the behavior

**Comment by thatJavaNerd** [comment]
I'm going to close this PR. I think it's an excellent idea, but the implementation doesn't fit snugly into the design of there rest of the library. Thank you to everyone involved.

**Pull request closed without merging**
