### PR TITLE
FIX: correctly calculate if refresh token is expired

### PR DESCRIPTION
**Pull request by Saketme**
This fixes https://github.com/thatJavaNerd/JRAW/issues/179

@thatJavaNerd I'm slightly concerned about migration of clients because this introduces a new field to be stored along with access tokens in SharedPreferences. 

Update: ugh, I forgot to run the tests. I will do this tomorrow.

### CODE REVIEW

**Comment by thatJavaNerd** [comment]
Looks good, thanks!

Sorry for the late response, I've been slacking on this project

**Comment by Saketme** [comment]
I understand, it must be a difficult job to maintain a library. Did you run the tests btw? I haven't been able to work on authentication since I submitted this PR.

**Comment by jorgegil96** [comment]
What does this change mean for clients not using the AuthenticationManager?  
I saw that in `OAuthData.java getExpirationDate()` was removed and `getExpirationDurationMillis()` was added.  
Am I right in assuming that I should now also save the expiration date myself in sharedprefs by adding the expiration duration millis to the current date **immediately** after authenticating?

**Comment by Saketme** [comment]
@jorgegil96 if you're not using `AuthenticationManager`, how are you calculating the time to refresh the access token?

**Comment by ccrama** [comment]
They probably do what I do and store the current time in millis + the
lifetime of the token, and refresh in the app once that time in millis has
been passed.

On Apr 24, 2017 2:20 PM, "Saket Narayan" <notifications@github.com> wrote:

@jorgegil96 <https://github.com/jorgegil96> if you're not using
AuthenticationManager, how are you calculating the time to refresh the
access token?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thatJavaNerd/JRAW/pull/180#issuecomment-296795425>, or mute
the thread

**Comment by jorgegil96** [comment]
Well I was going to use OAuthData.getExpirationDate() until I found out that it didn't work which led me to find this issue.  
What I'm doing now is what @ccrama described (current time millis + data("expires_in", Integer.class) * 1000).

**Comment by Saketme** [comment]
Ah okay. If you haven't started implementing your own custom logic, you can also choose to use JRAW now that this is fixed. There's also another PR related to refreshing tokens though:

https://github.com/thatJavaNerd/JRAW/pull/183

**Pull request merged**
