### PR TITLE
Added isQuarantine() check to Subreddit

### PR DESCRIPTION
**Pull request by mc-frank**
Checks if subreddit is quarantined or not

### CODE REVIEW

**Comment by thatJavaNerd** [comment]
Thanks! Are the changes to the gradle-related files intentional?

**Comment by mc-frank** [comment]
Oh nuts. Nope, I didn't mean to commit the gradle-files, but they were accidentally!

**Comment by mc-frank** [comment]
@thatJavaNerd would you like me to remove the files and re-commit it?

**Comment by thatJavaNerd** [comment]
Yes please. If the changes to the gradle files are necessary then it should be done in a separate commit/pull request.

**Pull request closed without merging**
