### PR TITLE
Various Bug Fixes

### PR DESCRIPTION
**Pull request by aprilhem**

### CODE REVIEW

**Comment by ccrama** [comment]
Are those all commits from my repo? If so, many of them are not implemented 100% correctly and I implemented some personal stuff in there, and you also included Slide's Jitpack config as well.

**Comment by thatJavaNerd** [comment]
I will not be merging this pull request because of a few changes the author of these commits choose to integrate. Specifically:

- Making `JsonModel`s mutable by introducing unecessary local fields ([here](https://github.com/ccrama/JRAW/blob/master/src/main/java/net/dean/jraw/models/Submission.java#L25), [here](https://github.com/ccrama/JRAW/blob/master/src/main/java/net/dean/jraw/models/Submission.java#L23))
- Vague method naming ([here](https://github.com/ccrama/JRAW/blob/master/src/main/java/net/dean/jraw/RedditClient.java#L96)).
- Removal of FindBugs
- Inconsistent formatting
- Unnecessary [`local.properties`](https://github.com/ccrama/JRAW/blob/master/local.properties)

If either you or @ccrama wish to address these issues I would be happy to merge that pull request.

**Comment by ccrama** [comment]
@thatJavaNerd Yeah that was never meant to be merged into JRAW. I will be making a new fork with various fixes (sorting of non-submission paginators), addition of stickying comments, saving stored links (gold), approving/removing comments, setting submission flair, and more here soon!

**Comment by thatJavaNerd** [comment]
Great news, thanks for your efforts!

**Pull request closed without merging**
